baseURL = 'https://example.org/'
draft = true
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'stack'

[params]
    mainSections = ["posts"]
    
    [params.sidebar]
        subtitle = "Blog about history, computer and travel"
        avatar = { enabled = true, local = true, src = "img/avatar.png" }

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]
        page = [
            { type = "toc" }
        ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

      