baseURL = 'https://mysite-ci3.pages.dev/'
draft = false
languageCode = 'ru-ru'
title = 'Sergey Ryazanov'
theme = 'stack'

[params]
    mainSections = ["posts"]
    
    [params.sidebar]
        subtitle = "My life"
        avatar = { enabled = true, local = false, src = "/img/logo.png" }
        favicon = "/img/logo.png"

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "remark42-last-comments" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]
        page = [
            { type = "toc" }
        ]

    [params.comments]
        enabled = true
        provider = "remark42"
    
        [params.comments.remark42]
            host = "https://remark42.iamqq.mywire.org"
            site = "mysite-ci3"
            locale = "ru"
            components = ["embed", "last-comments"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

      