baseURL = 'https://mysite-ci3.pages.dev/'
draft = false
languageCode = 'ru-ru'
title = 'Sergey Ryazanov'
theme = 'stack'

[params]
    mainSections = ["posts"]
    
    [params.sidebar]
        subtitle = "My life"
        avatar = { enabled = true, local = false, src = "/img/logo.png" }
        favicon = "/img/logo.png"

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]
        page = [
            { type = "toc" }
        ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

      